--- 
exp_arguments:
  n_classes: 2
  save_exp_code: lung_ad_sq_amil_resnet_fs
  raw_save_dir: heatmaps/heatmap_raw_results
  production_save_dir: heatmaps/heatmap_production_results
  batch_size: 128
data_arguments: 
  data_dir: data/bwh_lung_microscopy_img_crop
  process_list: bwh_lung_microscopy_FS_ad_sq.csv
  preset: presets/bwh.csv
  slide_ext: .tiff
  label_dict:
    ACA: 0
    SCC: 1                               
patching_arguments:
  patch_size: 256
  overlap: 0.95
  patch_level: 0
  custom_downsample: 1
model_arguments: 
  ckpt_path: results/lung_adeno_squam/lung_adeno_squam_resnet_amil_auc/s_0_checkpoint.pt
  model_type: attention_mil
  model_size: small
  drop_out: true
  enc_name: 'resnet50'
  encoding_size: 1024
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 0
  
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.4
  
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  
  # file extension for saving heatmap
  save_ext: jpg
  
  # whether to calculate percentile scores in reference to the set of all patches in all ROIs
  use_ref_scores: true
  
  # whether to use gaussian blur for further smoothing
  blur: true
  
  # whether to shift the 4 default points for checking if a patch is inside a foreground contour
  use_center_shift: true
  
  # whether to binarize attention scores
  binarize: false
  
  # binarization threshold: (0, 1)
  binary_thresh: 0.9
  
  # downscale factor for final heatmap 
  custom_downsample: 1

  # colormap
  cmap: 'jet'




