--- 
exp_arguments:
  n_classes: 2
  save_exp_code: speed_test_mobilenet
  raw_save_dir: heatmaps/heatmap_raw_results
  production_save_dir: heatmaps/heatmap_production_results
  batch_size: 128
data_arguments: 
  data_dir: data/bwh_lung_test_data_for_bowen
  process_list: bwh_lung_test_data_for_bowen.csv
  preset: presets/bwh.csv
  slide_ext: .tiff
  label_dict:
    primary: 1
    normal: 0                              
patching_arguments:
  patch_size: 256
  overlap: 0.
  patch_level: 0
  custom_downsample: 1
model_arguments: 
  ckpt_path: results/lung_tumor_normal/lung_tumor_normal_mobilenet_amil_auc/s_0_checkpoint.pt
  model_type: attention_mil
  model_size: small
  drop_out: true
  enc_name: 'mobilenetv3'
  encoding_size: 1280
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 0
  
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.5
  
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  
  # file extension for saving heatmap
  save_ext: jpg
  
  # whether to calculate percentile scores in reference to the set of all patches in all ROIs
  use_ref_scores: true
  
  # whether to use gaussian blur for further smoothing
  blur: false
  
  # whether to shift the 4 default points for checking if a patch is inside a foreground contour
  use_center_shift: true
  
  # whether to binarize attention scores
  binarize: false
  
  # binarization threshold: (0, 1)
  binary_thresh: 0.9
  
  # downscale factor for final heatmap 
  custom_downsample: 1

  # colormap
  cmap: 'coolwarm'




